# Generated by Django 4.2.4 on 2023-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_chats",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(related_name="chats", to="users.userprofile"),
        ),
    ]
